url_shortener/models.py
from .extensions import db
from datetime import datetime
import string
from random import choices


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(1024))
    short_url = db.Column(db.String(6), unique=True)
    views = db.Column(db.Integer, default=0)
    date_create = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()


    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=6))

        link = self.query.filter_by(short_url=short_url).first()

        if link:
            return self.generate_short_link()

        return short_url

url_shortener/__init__.py
from flask import Flask
from .extensions import db
from .routes import shortener

def create_app(config_file = 'settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    from . import models
    with app.app_context():
        db.create_all()

    app.register_blueprint(shortener)

    return app

url_shortener/auth.py
from functools import wraps
from flask import request, Response, current_app

def check_auth(username, password):
    return username == current_app.config['ADMIN_USERNAME'] and password == current_app.config['ADMIN_PASSWORD']

def authenticate():
    return Response(
        'Could you verify your access level\n'
        'You have to log in with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})

def require_auth(f):
    @wraps(f)
    def decored(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decored

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from .extensions import db
from .models import Link

from .auth import require_auth

shortener = Blueprint('shortener', __name__)

@shortener.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()
    link.views = link.views + 1
    db.session.commit()
    return redirect(link.original_url)

@shortener.route('/create_link', methods=['POST'])
def create_link():
    original_url = request.form['original_url']
    parts = original_url.split('?', 1)
    if len(parts) > 1:
        parsed_url = '?'.join([parts[0], '&'.join(sorted(parts[1].split('&')))])
    else:
        parsed_url = original_url

    res = db.session.query(Link).filter_by(original_url=parsed_url).all()
    if len(res) != 0:
        link = res[0]
    else:
        link = Link(original_url=parsed_url)
        db.session.add(link)
        db.session.commit()

    return render_template('link_success.html', new_url=link.short_url, original_url=original_url)

@shortener.route('/')
def index():
    return render_template('index.html')

@shortener.route('/analytics')
@require_auth
def analytics():
    links = Link.query.all()

    return render_template('analytics.html', links=links)

@shortener.errorhandler(404)
def page_not_found(e):
    return '<h1>Page Not Found 404</h1>', 404

@shortener.route("/clear")
def clear():
    Link.query.delete()
    db.session.commit()
    return redirect("/analytics")

url_shortener/templates/analytics.html
{% for link in links %}
    <p class="text-left" style="cursor: pointer; margin: 20px; padding: 6px; border-radius: 8px; font-size: 22px; background-color: rgb(154, 155, 199); max-width: 800px;">
        Original URL: {{ link.original_url }} | Short URL: {{ link.short_url }} | Views: {{ link.views }}
    </p>
{% endfor %}
<a href="clear">Clear Links</a>

url_shortener/templates/index.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<form method="POST" action="{{ url_for('shortener.create_link') }}" style="max-width: 800px; margin: 50px;">
    <div class="form-group">
        <label for="original-url" style="font-size: 28px;">
            Original URL
        </label>
        <input type="text" class="form-control" placeholder="Enter URL" name="original_url"/>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

url_shortener/templates/link_success.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<p class="text-left" style="cursor: pointer; margin: 20px; padding: 6px; border-radius: 8px; font-size: 22px; background-color: rgb(154, 155, 199); max-width: 800px;">
    Original URL: {{ original_url }}
</p>
<p class="text-left" style="cursor: pointer; margin: 20px; padding: 6px; border-radius: 8px; font-size: 22px; background-color: rgb(154, 155, 199); max-width: 800px;">
    Short URL: <a href="{{ url_for('shortener.redirect_to_url', short_url=new_url, _external=True) }}">{{ url_for('shortener.redirect_to_url', short_url=new_url, _external=True) }}</a>
</p>